version: "3.9"
services:
  machine-vision-plc:
    build: ./
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    networks:
      - docker_network
volumes:
  images:
    driver: local
networks:
  docker_network:
    driver: bridge
